# Site
repository: tailorck/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Chirag Tailor
# email: chiragktailor@gmail.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: tailorck
instagram_username: ctailor
linkedin_username: ctailor

# Additional icon links
additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_images:
  - title: Ronin
    path: images/me_and_ronin.png
  - title: Longvue
    path: images/longvue.jpg
  - title: Greener
    path: images/greener.jpg
  - title: Parth
    path: images/me_and_parth.jpg
  - title: Priyanka
    path: images/priyanka.jpg

# about_content: | # this will include new lines to allow paragraphs
#   Hi, I am Chirag.

content:
  - title: Birth # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Birth Place
        sub_title: Daytona Beach, FL

      - layout: top-middle
        title: Birth Date
        sub_title: November 23, 1993

  - title: Bio # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Height
        sub_title: 6'0"

      - layout: top-middle
        title: Weight
        sub_title: 170 lbs

      - layout: top-middle
        title: Hometown
        sub_title: Knoxville, TN

      - layout: top-middle
        title: Residing in
        sub_title: Atlanta, GA

  - title: Family # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Father
        sub_title: Kishor J. Tailor
        caption: Knoxville, TN / Dhamdachha, GJ

      - layout: top-middle
        title: Mother
        sub_title: Beena K. Tailor
        caption: Knoxville, TN / Vadodara, GJ

      - layout: top-middle
        title: Brother
        sub_title: Kishan K. Tailor
        caption: MSc Computer Science Candidate

  - title: Career # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Senior Software Engineer
        caption: 2021-Present
        sub_title: Twitter, Inc.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Georgia Institute of Technology
        caption: 2015 - 2017
        sub_title: MSc Computer Science
      - layout: top-middle
        title: University of Tennessee Knoxville
        caption: 2011 - 2015
        sub_title: BSc Electrical Engineering

  - title: A Little More About Me
    layout: text
    content: |
      Some of my other interests and hobbies are:
      - Running & Fitness
      - Podcasts
      - Piano
      - Baking

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: tailorck/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
