# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Chirag Tailor
# email: chiragktailor@gmail.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: tailorck
instagram_username: ctailor
linkedin_username: ctailor

# Additional icon links
additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
# about_content: | # this will include new lines to allow paragraphs
#   Hi, I am Chirag.

content:
  - title: Birth # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: center
        title: Birth Place
        sub_title: Daytona Beach, FL

      - layout: center
        title: Birth Date
        sub_title: November 23, 1993

  - title: Birth # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: center
        title: Height
        sub_title: 6ft 0in

      - layout: center
        title: Weight
        sub_title: 170 lbs

      - layout: center
        title: Hometown
        sub_title: Knoxville, TN

      - layout: center
        title: Residing in
        sub_title: Atlanta, GA

  - title: Family # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: center
        title: Father
        sub_title: Kishor J. Tailor

      - layout: center
        title: Mother
        sub_title: Beena K. Tailor

      - layout: center
        title: Brother
        sub_title: Kishan K. Tailor
        caption: MSc Computer Science Candidate - Cornell Tech

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: center
        title: Georgia Institute of Technology
        caption: 2015 - 2017
        sub_title: MSc Computer Science
      - layout: center
        title: University of Tennessee Knoxville
        caption: 2011 - 2015
        sub_title: BSc Electrical Engineering

  - title: A Little More About Me
    layout: text
    content: |
      Some of my other interests and hobbies are:
      - Baking
      - Running 
      - Fitness
      - Piano

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
